export const TIMEZONE_OPTIONS = [
  { value: -12, labelKey: 'UTC-12' },
  { value: -11, labelKey: 'UTC-11' },
  { value: -10, labelKey: 'timestamp.tzHawaii', prefix: 'UTC-10' },
  { value: -9, labelKey: 'timestamp.tzAlaska', prefix: 'UTC-9' },
  { value: -8, labelKey: 'timestamp.tzPacific', prefix: 'UTC-8' },
  { value: -7, labelKey: 'timestamp.tzMountain', prefix: 'UTC-7' },
  { value: -6, labelKey: 'timestamp.tzCentral', prefix: 'UTC-6' },
  { value: -5, labelKey: 'timestamp.tzEastern', prefix: 'UTC-5' },
  { value: -4, labelKey: 'timestamp.tzAtlantic', prefix: 'UTC-4' },
  { value: -3, labelKey: 'timestamp.tzBrazil', prefix: 'UTC-3' },
  { value: -2, labelKey: 'UTC-2' },
  { value: -1, labelKey: 'UTC-1' },
  { value: 0, labelKey: 'timestamp.tzLondon', prefix: 'UTC+0' },
  { value: 1, labelKey: 'timestamp.tzParis', prefix: 'UTC+1' },
  { value: 2, labelKey: 'timestamp.tzCairo', prefix: 'UTC+2' },
  { value: 3, labelKey: 'timestamp.tzMoscow', prefix: 'UTC+3' },
  { value: 4, labelKey: 'timestamp.tzDubai', prefix: 'UTC+4' },
  { value: 5, labelKey: 'timestamp.tzPakistan', prefix: 'UTC+5' },
  { value: 5.5, labelKey: 'timestamp.tzIndia', prefix: 'UTC+5:30' },
  { value: 6, labelKey: 'timestamp.tzBangladesh', prefix: 'UTC+6' },
  { value: 7, labelKey: 'timestamp.tzBangkok', prefix: 'UTC+7' },
  { value: 8, labelKey: 'timestamp.tzTaipei', prefix: 'UTC+8' },
  { value: 9, labelKey: 'timestamp.tzTokyo', prefix: 'UTC+9' },
  { value: 9.5, labelKey: 'timestamp.tzAustraliaCentral', prefix: 'UTC+9:30' },
  { value: 10, labelKey: 'timestamp.tzSydney', prefix: 'UTC+10' },
  { value: 11, labelKey: 'UTC+11' },
  { value: 12, labelKey: 'timestamp.tzNewZealand', prefix: 'UTC+12' }
];
