/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {};

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BaseCard: typeof import('./components/common/BaseCard.vue')['default']
    CommandPalette: typeof import('./components/common/CommandPalette.vue')['default']
    HistoryList: typeof import('./components/common/HistoryList.vue')['default']
    InputWithCopy: typeof import('./components/common/InputWithCopy.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Toast: typeof import('./components/common/Toast.vue')['default']
    ToolContext: typeof import('./components/common/ToolContext.vue')['default']
    TwoWayConverter: typeof import('./components/common/TwoWayConverter.vue')['default']
  }
}
