/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection ES6UnusedImports
// Generated by unplugin-vue-router. !! DO NOT MODIFY THIS FILE !!
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-resolver' {
  export type ParamParserCustom = never
}

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne
  } from 'vue-router';

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/Base64Converter': RouteRecordInfo<
      '/Base64Converter',
      '/Base64Converter',
      Record<never, never>,
      Record<never, never>,
      never
    >;
    '/ColorConverter': RouteRecordInfo<
      '/ColorConverter',
      '/ColorConverter',
      Record<never, never>,
      Record<never, never>,
      never
    >;
    '/common/BaseCard': RouteRecordInfo<
      '/common/BaseCard',
      '/common/BaseCard',
      Record<never, never>,
      Record<never, never>,
      never
    >;
    '/common/CommandPalette': RouteRecordInfo<
      '/common/CommandPalette',
      '/common/CommandPalette',
      Record<never, never>,
      Record<never, never>,
      never
    >;
    '/common/HistoryList': RouteRecordInfo<
      '/common/HistoryList',
      '/common/HistoryList',
      Record<never, never>,
      Record<never, never>,
      never
    >;
    '/common/InputWithCopy': RouteRecordInfo<
      '/common/InputWithCopy',
      '/common/InputWithCopy',
      Record<never, never>,
      Record<never, never>,
      never
    >;
    '/common/Toast': RouteRecordInfo<
      '/common/Toast',
      '/common/Toast',
      Record<never, never>,
      Record<never, never>,
      never
    >;
    '/common/ToolContext': RouteRecordInfo<
      '/common/ToolContext',
      '/common/ToolContext',
      Record<never, never>,
      Record<never, never>,
      never
    >;
    '/common/TwoWayConverter': RouteRecordInfo<
      '/common/TwoWayConverter',
      '/common/TwoWayConverter',
      Record<never, never>,
      Record<never, never>,
      never
    >;
    '/DiffChecker': RouteRecordInfo<
      '/DiffChecker',
      '/DiffChecker',
      Record<never, never>,
      Record<never, never>,
      never
    >;
    '/DurationCalculator': RouteRecordInfo<
      '/DurationCalculator',
      '/DurationCalculator',
      Record<never, never>,
      Record<never, never>,
      never
    >;
    '/HashGenerator': RouteRecordInfo<
      '/HashGenerator',
      '/HashGenerator',
      Record<never, never>,
      Record<never, never>,
      never
    >;
    '/icons/SvgIcon': RouteRecordInfo<
      '/icons/SvgIcon',
      '/icons/SvgIcon',
      Record<never, never>,
      Record<never, never>,
      never
    >;
    '/JsonFormatter': RouteRecordInfo<
      '/JsonFormatter',
      '/JsonFormatter',
      Record<never, never>,
      Record<never, never>,
      never
    >;
    '/JwtDebugger': RouteRecordInfo<
      '/JwtDebugger',
      '/JwtDebugger',
      Record<never, never>,
      Record<never, never>,
      never
    >;
    '/PinyinConverter': RouteRecordInfo<
      '/PinyinConverter',
      '/PinyinConverter',
      Record<never, never>,
      Record<never, never>,
      never
    >;
    '/QrCodeGenerator': RouteRecordInfo<
      '/QrCodeGenerator',
      '/QrCodeGenerator',
      Record<never, never>,
      Record<never, never>,
      never
    >;
    '/TimestampConverter': RouteRecordInfo<
      '/TimestampConverter',
      '/TimestampConverter',
      Record<never, never>,
      Record<never, never>,
      never
    >;
    '/UnicodeConverter': RouteRecordInfo<
      '/UnicodeConverter',
      '/UnicodeConverter',
      Record<never, never>,
      Record<never, never>,
      never
    >;
    '/UrlConverter': RouteRecordInfo<
      '/UrlConverter',
      '/UrlConverter',
      Record<never, never>,
      Record<never, never>,
      never
    >;
    '/UuidGenerator': RouteRecordInfo<
      '/UuidGenerator',
      '/UuidGenerator',
      Record<never, never>,
      Record<never, never>,
      never
    >;
  }

  /**
   * Route file to route info map by unplugin-vue-router.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/components/Base64Converter.vue': {
      routes: '/Base64Converter';
      views: never;
    };
    'src/components/ColorConverter.vue': {
      routes: '/ColorConverter';
      views: never;
    };
    'src/components/common/BaseCard.vue': {
      routes: '/common/BaseCard';
      views: never;
    };
    'src/components/common/CommandPalette.vue': {
      routes: '/common/CommandPalette';
      views: never;
    };
    'src/components/common/HistoryList.vue': {
      routes: '/common/HistoryList';
      views: never;
    };
    'src/components/common/InputWithCopy.vue': {
      routes: '/common/InputWithCopy';
      views: never;
    };
    'src/components/common/Toast.vue': {
      routes: '/common/Toast';
      views: never;
    };
    'src/components/common/ToolContext.vue': {
      routes: '/common/ToolContext';
      views: never;
    };
    'src/components/common/TwoWayConverter.vue': {
      routes: '/common/TwoWayConverter';
      views: never;
    };
    'src/components/DiffChecker.vue': {
      routes: '/DiffChecker';
      views: never;
    };
    'src/components/DurationCalculator.vue': {
      routes: '/DurationCalculator';
      views: never;
    };
    'src/components/HashGenerator.vue': {
      routes: '/HashGenerator';
      views: never;
    };
    'src/components/icons/SvgIcon.vue': {
      routes: '/icons/SvgIcon';
      views: never;
    };
    'src/components/JsonFormatter.vue': {
      routes: '/JsonFormatter';
      views: never;
    };
    'src/components/JwtDebugger.vue': {
      routes: '/JwtDebugger';
      views: never;
    };
    'src/components/PinyinConverter.vue': {
      routes: '/PinyinConverter';
      views: never;
    };
    'src/components/QrCodeGenerator.vue': {
      routes: '/QrCodeGenerator';
      views: never;
    };
    'src/components/TimestampConverter.vue': {
      routes: '/TimestampConverter';
      views: never;
    };
    'src/components/UnicodeConverter.vue': {
      routes: '/UnicodeConverter';
      views: never;
    };
    'src/components/UrlConverter.vue': {
      routes: '/UrlConverter';
      views: never;
    };
    'src/components/UuidGenerator.vue': {
      routes: '/UuidGenerator';
      views: never;
    };
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info> ? Info['routes'] : keyof RouteNamedMap;
}
